name: Compilar Web (Acceso Safari Directo)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: false

      - name: Habilitar Web y regenerar soporte
        run: |
          flutter config --enable-web
          flutter create --platforms=web .
          flutter pub get

      - name: Compilar Web PWA
        run: flutter build web --release --base-href "/control_vehicularBomberos/" --web-renderer html --no-tree-shake-icons

      - name: Publicar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
